apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ss-utopia-account
  name: ss-utopia-account
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ss-utopia-account
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/mynetwork: "true"
        io.kompose.service: ss-utopia-account
    spec:
      containers:
      - env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://ss-utopia-eureka:8761/eureka/
        image: "{{ .Values.aws.account_id }}.dkr.ecr.{{ .Values.aws.region }}/ss-utopia-account:latest"
        imagePullPolicy: "Always"
        name: ss-utopia-account
        ports:
        - containerPort: 8088
        resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
