
Resources:
  ECSCluster:  
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: 
        - FARGATE
      ClusterName: ss-microservice-cluster
      DefaultCapacityProviderStrategy: 
        - CapacityProvider: FARGATE
          Weight: 1
      