Parameters:
  ECSClusterName:
    Type: String
    Default: ss-microservice-cluster
    Description: Name of the ECS Cluster
  Certificate:
    Description: AWS Defined certificate arn
    Type: String
    Default: arn:aws:acm:us-east-1:422288715120:certificate/a3761ff8-2b71-4211-baf3-794ab4c941d9
  VpcId:
    Description: ID of the VPC for the cluster
    Type: AWS::EC2::VPC::Id
    Default: vpc-0539fcbee603aa06f
  SecurityGroupId:
    Description: Id of Security Group Id for the microservices(services)
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-084f7c02034e43647
  PublicSubnetList:
    Description: list of subnets for the loadbalancer to live
    Type: String
    Default: subnet-06ccffc4220634064,subnet-0be0fcb5a5e935938
  PrivateSubnetList:
    Description: list of subnets for the microservices to live
    Type: String
    Default: subnet-03a8fad58b369f014,subnet-06f80c11bb1c4fb16  
  HostedZoneId:
    Description: id of the hosted zone for route53 record
    Type: AWS::Route53::HostedZone::Id
    Default: Z05979981EHQ1LXTHAH2G
  AuthTaskDef:
    Description: The task definistion for the auth service to use
    Type: String
    Default: ss-utopia-auth:4
  LoanTaskDef:
    Description: The task definistion for the loan service to use
    Type: String
    Default: ss-utopia-loan:1
  AccountTaskDef:
    Description: The task definistion for the account service to use
    Type: String
    Default: ss-utopia-account:5
  UserTaskDef:
    Description: The task definistion for the user service to use
    Type: String
    Default: ss-utopia-user:1


Resources:

  ECSCluster:  
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: 
        - FARGATE
      ClusterName: 
        Ref: ECSClusterName
      DefaultCapacityProviderStrategy: 
        - CapacityProvider: FARGATE
          Weight: 1

  ListenerAccount:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: 
      - TargetGroupAcct
      - LoadBlancer
    Properties: 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref TargetGroupAcct
      LoadBalancerArn: !Ref LoadBlancer
      Port: 8088
      Protocol: HTTPS
      Certificates:
        - Ref: Certificate
  TargetGroupAcct:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Port: 8088
      Protocol: HTTPS
      VpcId: 
        Ref: VpcId
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTPS
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Name: acct-dev
      ProtocolVersion: HTTP1
      TargetType: ip
  ServiceAcct:
    Type: AWS::ECS::Service
    DependsOn: 
      - ListenerAccount
      - LoadBlancer
      - ECSCluster
    Properties: 
      Cluster: !Ref ECSCluster
      DesiredCount: 2
      HealthCheckGracePeriodSeconds: 120
      LaunchType: FARGATE
      LoadBalancers: 
        - TargetGroupArn:
            Ref: TargetGroupAcct
          ContainerPort: 8088
          ContainerName: ss-utopia-account
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: ENABLED
          SecurityGroups: 
            - Ref: SecurityGroupId
          Subnets: 
            !Split [",", !Ref PrivateSubnetList]
      ServiceName: ServiceAcct
      TaskDefinition: 
        Ref: AccountTaskDef


  ListenerLoan:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: 
      - TargetGroupLoan
      - LoadBlancer
    Properties: 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref TargetGroupLoan
      LoadBalancerArn: !Ref LoadBlancer
      Port: 8084
      Protocol: HTTPS
      Certificates:
        - Ref: Certificate
  TargetGroupLoan:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Port: 8084
      Protocol: HTTPS
      VpcId: 
        Ref: VpcId
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTPS
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Name: loan-dev
      ProtocolVersion: HTTP1
      TargetType: ip
  ServiceLoan:
    Type: AWS::ECS::Service
    DependsOn: 
      - ListenerLoan
      - LoadBlancer
      - ECSCluster
    Properties: 
      Cluster: !Ref ECSCluster
      DesiredCount: 2
      HealthCheckGracePeriodSeconds: 120
      LaunchType: FARGATE
      LoadBalancers: 
        - TargetGroupArn:
            Ref: TargetGroupLoan
          ContainerPort: 8084
          ContainerName: ss-utopia-loan
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: ENABLED
          SecurityGroups: 
            - Ref: SecurityGroupId
          Subnets: 
            !Split [",", !Ref PrivateSubnetList]
      ServiceName: ServiceLoan
      TaskDefinition: 
        Ref: LoanTaskDef



  ListenerUser:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: 
      - TargetGroupUser
      - LoadBlancer
    Properties: 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref TargetGroupUser
      LoadBalancerArn: !Ref LoadBlancer
      Port: 8089
      Protocol: HTTPS
      Certificates:
        - Ref: Certificate
  TargetGroupUser:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Port: 8089
      Protocol: HTTPS
      VpcId: 
        Ref: VpcId
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTPS
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Name: User-dev
      ProtocolVersion: HTTP1
      TargetType: ip
  ServiceUser:
    Type: AWS::ECS::Service
    DependsOn: 
      - ListenerUser
      - LoadBlancer
      - ECSCluster
    Properties: 
      Cluster: !Ref ECSCluster
      DesiredCount: 2
      HealthCheckGracePeriodSeconds: 120
      LaunchType: FARGATE
      LoadBalancers: 
        - TargetGroupArn:
            Ref: TargetGroupUser
          ContainerPort: 8089
          ContainerName: ss-utopia-users
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: ENABLED
          SecurityGroups: 
            - Ref: SecurityGroupId
          Subnets: 
            !Split [",", !Ref PrivateSubnetList]
      ServiceName: ServiceUser
      TaskDefinition: 
        Ref: UserTaskDef
  

  ListenerAuth:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: 
      - TargetGroupAuth
      - LoadBlancer
    Properties: 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref TargetGroupAuth
      LoadBalancerArn: !Ref  LoadBlancer
      Port: 8443
      Protocol: HTTPS
      Certificates:
        - Ref: Certificate
  TargetGroupAuth:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Port: 8443
      Protocol: HTTP
      VpcId: 
        Ref: VpcId
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Name: Auth-dev
      ProtocolVersion: HTTP1
      TargetType: ip
  ServiceAuth:
    Type: AWS::ECS::Service
    DependsOn: 
      - ListenerAuth
      - LoadBlancer
      - ECSCluster
    Properties: 
      Cluster: !Ref ECSCluster
      DesiredCount: 2
      HealthCheckGracePeriodSeconds: 120
      LaunchType: FARGATE
      LoadBalancers: 
        - TargetGroupArn:
            Ref: TargetGroupAuth
          ContainerPort: 8443
          ContainerName: ss-utopia-auth
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: ENABLED
          SecurityGroups: 
            - Ref: SecurityGroupId
          Subnets: 
            !Split [",", !Ref PrivateSubnetList]
      ServiceName: ServiceAuth
      TaskDefinition: 
        Ref: AuthTaskDef


  LoadBlancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: ecsLB
      Scheme: internet-facing
      SecurityGroups: 
            - Ref: SecurityGroupId
      Subnets: 
            !Split [",", !Ref PublicSubnetList]
  
  routeRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: 
      - LoadBlancer
    Properties: 
      AliasTarget: 
        DNSName: !GetAtt LoadBlancer.DNSName
        HostedZoneId: !GetAtt LoadBlancer.CanonicalHostedZoneID
      HostedZoneId: 
        Ref: HostedZoneId
      Name: api.utopia-financial.com
      Type: A