- name: delete loadbalancer and Configure Route 53
  hosts: localhost
  vars:

  

  tasks:
    - name: Retrieve the details for api.utopia-financial.com
      community.aws.route53:
        state: get
        zone: utopia-financial.com
        record: api.utopia-financial.com
        type: A
      register: rec
    - name: Delete api.utopia-financial.com A record using the results from the get command
      community.aws.route53:
        state: absent
        zone: utopia-financial.com
        record: "{{ rec.set.record }}"
        type: "{{ rec.set.type }}"
        value: "{{ rec.set.value }}"
        alias: True
        alias_hosted_zone_id: "{{ rec.set.alias_hosted_zone_id }}"
    - name: LB delete
      community.aws.elb_application_lb:
        name: ecs-alb
        state: absent
        


- name: Delete ECS cluster inside vpc
  hosts: localhost
  vars:
    ecs_cluster_name: 'ss-microservice-cluster'
  tasks: 
    - name: Cluster Delete
      community.aws.ecs_cluster:
        name: "{{ ecs_cluster_name }}"
        state: absent  