
- name: Setup EKS cluster 
  hosts: localhost
  vars:
    eks_cluster_name: 'ss-microservice-cluster_eks'
    security_groups_cluster: 
      - sg-084f7c02034e43647
    subnets_cluster:
      - subnet-03a8fad58b369f014
      - subnet-06f80c11bb1c4fb16
  tasks: 
  - name: creating eks cluster
    community.aws.aws_eks_cluster:
      name: "{{ eks_cluster_name }}"
      version: 1.14
      subnets: "{{ subnets_cluster }}"
      security_groups: "{{ security_groups_cluster }}"
    register: cluster_out